# Generated by Django 5.2.3 on 2025-06-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keywords", models.CharField(max_length=200)),
                (
                    "location_filter",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("frequency", models.CharField(max_length=50)),
                ("last_sent", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
