# Generated by Django 5.2.3 on 2025-06-14 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0002_initial"),
        ("jobs", "0004_savedsearch_bookmark"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("criteria", models.JSONField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=50,
                    ),
                ),
                ("lastSent", models.DateTimeField(blank=True, null=True)),
                ("nextScheduled", models.DateTimeField(blank=True, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="JobAlertStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("totalAlerts", models.IntegerField(default=0)),
                ("activeAlerts", models.IntegerField(default=0)),
                ("matchesByFrequency", models.JSONField(default=dict)),
                ("matchesByStatus", models.JSONField(default=dict)),
                ("lastUpdated", models.DateTimeField(auto_now=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="alerts.jobalert",
                    ),
                ),
            ],
            options={
                "ordering": ["-lastUpdated"],
            },
        ),
        migrations.CreateModel(
            name="JobAlertMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matchScore", models.FloatField()),
                ("matchReasons", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("viewed", "Viewed"),
                            ("applied", "Applied"),
                            ("ignored", "Ignored"),
                        ],
                        default="new",
                        max_length=50,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="alerts.jobalert",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.joblisting",
                    ),
                ),
            ],
            options={
                "ordering": ["-matchScore"],
                "unique_together": {("alert", "job")},
            },
        ),
    ]
