# Generated by Django 5.2.3 on 2025-06-14 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_savedsearch_bookmark"),
        ("recommendations", "0002_alter_recommendation_job_jobrecommendation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matchScore", models.FloatField()),
                ("matchingSkills", models.JSONField()),
                ("missingSkills", models.JSONField()),
                ("skillGaps", models.JSONField()),
                ("recommendations", models.JSONField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.joblisting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-matchScore"],
                "unique_together": {("user", "job")},
            },
        ),
        migrations.CreateModel(
            name="JobSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarityScore", models.FloatField()),
                ("commonSkills", models.JSONField()),
                ("commonRequirements", models.JSONField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "job1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities_as_job1",
                        to="jobs.joblisting",
                    ),
                ),
                (
                    "job2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities_as_job2",
                        to="jobs.joblisting",
                    ),
                ),
            ],
            options={
                "ordering": ["-similarityScore"],
                "unique_together": {("job1", "job2")},
            },
        ),
    ]
