import { Job } from '../types';

// Mock Jobs
export const mockJobs: Job[] = [
  {
    id: 'job1',
    title: 'Senior Full Stack Developer',
    company: 'TechCorp Solutions',
    description: 'We are looking for a senior full stack developer to join our growing team. You will be responsible for developing and maintaining web applications using modern technologies.',
    requirements: [
      '5+ years of experience in web development',
      'Proficiency in JavaScript, React, and Node.js',
      'Experience with databases (PostgreSQL, MongoDB)',
      'Knowledge of cloud platforms (AWS, Azure)',
      'Strong problem-solving skills',
    ],
    benefits: [
      'Competitive salary and equity',
      'Health, dental, and vision insurance',
      'Flexible work arrangements',
      '401(k) with company matching',
      'Professional development budget',
    ],
    location: 'San Francisco, CA',
    salaryRange: { min: 120000, max: 160000 },
    jobType: 'full-time',
    experienceLevel: 'senior',
    industry: 'Technology',
    postedDate: '2024-01-18T10:00:00Z',
    applicationDeadline: '2024-02-18T23:59:59Z',
    isActive: true,
    companyLogo: 'https://via.placeholder.com/100x100?text=TC',
    skills: ['JavaScript', 'React', 'Node.js', 'PostgreSQL', 'AWS'],
    applicationCount: 23,
  },
  {
    id: 'job2',
    title: 'Frontend Developer',
    company: 'Digital Innovations',
    description: 'Join our team as a Frontend Developer and help create amazing user experiences for our clients.',
    requirements: [
      '3+ years of React experience',
      'Strong CSS and HTML skills',
      'Experience with TypeScript',
      'Knowledge of testing frameworks',
    ],
    benefits: [
      'Remote work options',
      'Health insurance',
      'Learning and development budget',
      'Flexible hours',
    ],
    location: 'New York, NY',
    salaryRange: { min: 85000, max: 110000 },
    jobType: 'full-time',
    experienceLevel: 'mid',
    industry: 'Technology',
    postedDate: '2024-01-20T14:00:00Z',
    isActive: true,
    companyLogo: 'https://via.placeholder.com/100x100?text=DI',
    skills: ['React', 'TypeScript', 'CSS', 'HTML', 'Jest'],
    applicationCount: 15,
  },
  {
    id: 'job3',
    title: 'Junior Python Developer',
    company: 'DataTech Analytics',
    description: 'Entry-level position for a Python developer interested in data analytics and machine learning.',
    requirements: [
      '1-2 years of Python experience',
      'Basic knowledge of pandas and numpy',
      'Understanding of SQL',
      'Bachelor\'s degree in Computer Science or related field',
    ],
    benefits: [
      'Mentorship program',
      'Health insurance',
      'Career growth opportunities',
      'Free lunch',
    ],
    location: 'Austin, TX',
    salaryRange: { min: 65000, max: 80000 },
    jobType: 'full-time',
    experienceLevel: 'junior',
    industry: 'Data Analytics',
    postedDate: '2024-01-22T09:00:00Z',
    isActive: true,
    companyLogo: 'https://via.placeholder.com/100x100?text=DTA',
    skills: ['Python', 'Pandas', 'NumPy', 'SQL', 'Machine Learning'],
    applicationCount: 31,
  },
  {
    id: 'job4',
    title: 'DevOps Engineer',
    company: 'CloudFirst Technologies',
    description: 'Seeking an experienced DevOps engineer to manage our cloud infrastructure and CI/CD pipelines.',
    requirements: [
      '4+ years of DevOps experience',
      'Experience with AWS/Azure/GCP',
      'Knowledge of Kubernetes and Docker',
      'Proficiency in Infrastructure as Code',
    ],
    benefits: [
      'Competitive salary',
      'Stock options',
      'Remote work',
      'Conference budget',
    ],
    location: 'Remote',
    salaryRange: { min: 110000, max: 140000 },
    jobType: 'full-time',
    experienceLevel: 'senior',
    industry: 'Cloud Computing',
    postedDate: '2024-01-19T11:00:00Z',
    isActive: true,
    companyLogo: 'https://via.placeholder.com/100x100?text=CFT',
    skills: ['AWS', 'Kubernetes', 'Docker', 'Terraform', 'Jenkins'],
    applicationCount: 18,
  },
  {
    id: 'job5',
    title: 'UX/UI Designer',
    company: 'Creative Studio Pro',
    description: 'Looking for a talented UX/UI designer to create beautiful and functional user interfaces.',
    requirements: [
      '3+ years of UX/UI design experience',
      'Proficiency in Figma and Adobe Creative Suite',
      'Understanding of user-centered design principles',
      'Portfolio showcasing diverse projects',
    ],
    benefits: [
      'Creative freedom',
      'Health insurance',
      'Flexible schedule',
      'Design tools budget',
    ],
    location: 'Los Angeles, CA',
    salaryRange: { min: 75000, max: 95000 },
    jobType: 'full-time',
    experienceLevel: 'mid',
    industry: 'Design',
    postedDate: '2024-01-21T13:00:00Z',
    isActive: true,
    companyLogo: 'https://via.placeholder.com/100x100?text=CSP',
    skills: ['Figma', 'Adobe XD', 'Photoshop', 'Illustrator', 'Prototyping'],
    applicationCount: 27,
  },
];