# Generated by Django 5.2.3 on 2025-06-14 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_education_options_alter_skill_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="resumes/versions/")),
                ("version_number", models.IntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_current", models.BooleanField(default=False)),
                ("parsed_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.RemoveIndex(
            model_name="skill",
            name="authenticat_name_4578b3_idx",
        ),
        migrations.RemoveIndex(
            model_name="skill",
            name="authenticat_categor_be7cb5_idx",
        ),
        migrations.RemoveIndex(
            model_name="userskill",
            name="authenticat_user_id_a5aa81_idx",
        ),
        migrations.RemoveIndex(
            model_name="userskill",
            name="authenticat_profici_216512_idx",
        ),
        migrations.AddField(
            model_name="skill",
            name="aliases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="skill",
            name="popularity_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("connections", "Connections Only"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="show_education",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="show_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="show_experience",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="show_location",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="show_phone",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="show_resume",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="show_skills",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="show_social_links",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userskill",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userskill",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_skills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resumeversion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resume_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="resumeversion",
            unique_together={("user", "version_number")},
        ),
    ]
