# Generated by Django 5.2.3 on 2025-06-14 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_resumeversion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "thumbnail",
                    models.ImageField(upload_to="resume_templates/thumbnails/"),
                ),
                ("templateFile", models.FileField(upload_to="resume_templates/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("creative", "Creative"),
                            ("simple", "Simple"),
                            ("modern", "Modern"),
                        ],
                        max_length=50,
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="resumeVersions",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="authentication.resumeversion"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="selectedTemplate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentication.resumetemplate",
            ),
        ),
    ]
