# Generated by Django 5.2.3 on 2025-06-14 15:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_resumeversion_and_more"),
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="posted_by",
        ),
        migrations.RemoveField(
            model_name="jobskill",
            name="job",
        ),
        migrations.RemoveField(
            model_name="jobskill",
            name="skill",
        ),
        migrations.AddField(
            model_name="company",
            name="industry",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(blank=True, upload_to="company_logos/"),
        ),
        migrations.AddField(
            model_name="company",
            name="size",
            field=models.CharField(
                choices=[
                    ("startup", "Startup"),
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("large", "Large"),
                ],
                default=django.utils.timezone.now,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="company",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name="JobListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
                ("benefits", models.TextField(blank=True)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior Level"),
                            ("executive", "Executive"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "remote_option",
                    models.CharField(
                        choices=[
                            ("on_site", "On-site"),
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=50,
                    ),
                ),
                ("posted_date", models.DateTimeField(auto_now_add=True)),
                ("application_deadline", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("view_count", models.IntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_listings",
                        to="jobs.company",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posted_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobSkillRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                (
                    "proficiency_level",
                    models.IntegerField(
                        choices=[
                            (1, "Beginner"),
                            (2, "Intermediate"),
                            (3, "Advanced"),
                            (4, "Expert"),
                        ]
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_requirements",
                        to="jobs.joblisting",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.skill",
                    ),
                ),
            ],
        ),
    ]
