# Generated by Django 5.2.3 on 2025-06-14 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0004_jobapplication_job_jobapplication_user_and_more"),
        ("jobs", "0002_remove_job_posted_by_remove_jobskill_job_and_more"),
        ("recommendations", "0002_alter_recommendation_job_jobrecommendation_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Job",
        ),
        migrations.DeleteModel(
            name="JobSkill",
        ),
        migrations.AlterUniqueTogether(
            name="jobskillrequirement",
            unique_together={("job", "skill")},
        ),
    ]
