# Generated by Django 5.2.3 on 2025-06-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("changed_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover_letter", models.TextField(blank=True)),
                (
                    "custom_resume",
                    models.FileField(blank=True, upload_to="application_resumes/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("reviewed", "Under Review"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("interviewed", "Interviewed"),
                            ("offered", "Offered"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="applied",
                    ),
                ),
                ("applied_date", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="application",
            name="job",
        ),
        migrations.RemoveField(
            model_name="application",
            name="user",
        ),
        migrations.RenameField(
            model_name="interview",
            old_name="scheduled_at",
            new_name="scheduled_date",
        ),
        migrations.AddField(
            model_name="interview",
            name="duration_minutes",
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name="interview",
            name="feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="interview",
            name="interviewer_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="interview",
            name="interview_type",
            field=models.CharField(
                choices=[
                    ("phone", "Phone"),
                    ("video", "Video"),
                    ("in_person", "In Person"),
                    ("technical", "Technical"),
                ]
            ),
        ),
    ]
