# Generated by Django 5.2.3 on 2025-06-14 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0003_applicationstatushistory_jobapplication_and_more"),
        ("jobs", "0002_remove_job_posted_by_remove_jobskill_job_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jobs.joblisting"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="applicationstatushistory",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="applications.jobapplication",
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="applications.jobapplication",
            ),
        ),
        migrations.DeleteModel(
            name="Application",
        ),
    ]
