# Generated by Django 5.2.3 on 2025-06-14 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0004_jobapplication_job_jobapplication_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technicalScore", models.FloatField()),
                ("communicationScore", models.FloatField()),
                ("problemSolvingScore", models.FloatField()),
                ("culturalFitScore", models.FloatField()),
                ("strengths", models.JSONField()),
                ("weaknesses", models.JSONField()),
                ("notes", models.TextField()),
                ("recommendations", models.JSONField()),
                ("nextSteps", models.JSONField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="applications.jobapplication",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="InterviewPreparation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resources", models.JSONField()),
                ("practiceQuestions", models.JSONField()),
                ("companyResearch", models.JSONField()),
                ("technicalTopics", models.JSONField()),
                ("softSkills", models.JSONField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preparation",
                        to="applications.jobapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="InterviewSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("meetingLink", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("reminders", models.JSONField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="applications.jobapplication",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="scheduled_interviews", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-createdAt"],
            },
        ),
    ]
